// ─── Référentiels vin ──────────────────────────────────────────────────────

export const COULEURS_VIN = [
  'rouge',
  'blanc',
  'rosé',
  'effervescent',
  'moelleux',
  'autre',
] as const;

export type CouleurVin = typeof COULEURS_VIN[number];

// Tous les formats de flacons (complet)
export const FORMATS_BOUTEILLE = [
  { value: 'quart',         label: 'Quart (18,75 cl)',        cl: 18.75 },
  { value: 'demi-bouteille',label: 'Demi-bouteille (37,5 cl)',cl: 37.5 },
  { value: 'bouteille',     label: 'Bouteille (75 cl)',        cl: 75 },
  { value: 'magnum',        label: 'Magnum (1,5 L)',           cl: 150 },
  { value: 'jéroboam',      label: 'Jéroboam (3 L)',           cl: 300 },
  { value: 'réhoboam',      label: 'Réhoboam (4,5 L)',         cl: 450 },
  { value: 'mathusalem',    label: 'Mathusalem (6 L)',          cl: 600 },
  { value: 'salmanazar',    label: 'Salmanazar (9 L)',          cl: 900 },
  { value: 'balthazar',     label: 'Balthazar (12 L)',          cl: 1200 },
  { value: 'nabuchodonosor',label: 'Nabuchodonosor (15 L)',     cl: 1500 },
  { value: 'melchior',      label: 'Melchior (18 L)',           cl: 1800 },
  { value: 'solomon',       label: 'Solomon (20 L)',            cl: 2000 },
  { value: 'souverain',     label: 'Souverain (25 L)',          cl: 2500 },
  { value: 'primat',        label: 'Primat (27 L)',             cl: 2700 },
  { value: 'melchizédec',   label: 'Melchizédec (30 L)',        cl: 3000 },
] as const;

export const FORMAT_VALUES = FORMATS_BOUTEILLE.map(f => f.value);
export type FormatBouteille = typeof FORMATS_BOUTEILLE[number]['value'];

export const PAYS = [
  'France',
  'Italie',
  'Espagne',
  'Portugal',
  'Allemagne',
  'Argentine',
  'Chili',
  'États-Unis',
  'Australie',
  'Autriche',
  'Afrique du Sud',
  'Nouvelle-Zélande',
  'Géorgie',
  'Grèce',
  'Hongrie',
  'Angleterre',
  'Arménie',
  'Brésil',
  'Bulgarie',
  'Canada',
  'Chine',
  'Croatie',
  'Inde',
  'Israël',
  'Japon',
  'Liban',
  'Luxembourg',
  'Macédoine',
  'Maroc',
  'Mexique',
  'Moldavie',
  'Pays-Bas',
  'République Tchèque',
  'Roumanie',
  'Serbie',
  'Slovaquie',
  'Slovénie',
  'Suisse',
  'Tunisie',
  'Turquie',
  'Uruguay',
  'Autre',
] as const;

export const REGIONS = [
  // France
  'Bordeaux',
  'Bourgogne',
  'Champagne',
  'Vallée du Rhône',
  'Côtes du Rhône',
  'Alsace',
  'Languedoc',
  'Provence',
  'Loire',
  'Jura',
  'Savoie',
  'Corse',
  'Sud-Ouest',
  'Beaujolais',
  'Bugey',
  'Charentes',
  'Côte Chalonnaise',
  'Côte de Beaune',
  'Côte de Nuits',
  'Coteaux du Lyonnais',
  'Côtes de Blaye',
  'Côtes de Bordeaux',
  'Côtes de Bourg',
  'Côtes de Duras',
  'Côtes de Gascogne',
  'Côtes du Ventoux',
  'Limoux',
  'Maconnais',
  'Pays Nantais',
  'Pyrénées-Atlantiques',
  'Roussillon',
  'Val de Loire',
  // Italie
  'Toscane',
  'Piémont',
  'Vénétie',
  'Sicile',
  'Sardaigne',
  'Lombardie',
  'Campanie',
  'Pouilles',
  'Ombrie',
  'Frioul',
  'Trentin-Haut-Adige',
  'Abruzzes',
  'Basilicate',
  'Calabre',
  // Espagne
  'Rioja',
  'Ribera del Duero',
  'Priorat',
  'Penedès',
  'Galice',
  'Rueda',
  'Bierzo',
  'Toro',
  'Jumilla',
  'Jerez',
  // Portugal
  'Douro',
  'Alentejo',
  'Vinho Verde',
  'Dão',
  'Bairrada',
  'Setubal',
  // Allemagne
  'Moselle (Allemagne)',
  'Rhin',
  'Rhénanie-Palatinat',
  'Bade',
  'Franconie',
  // États-Unis
  'Napa Valley',
  'Sonoma',
  'Willamette Valley',
  'Columbia Valley',
  'Central Coast',
  'Paso Robles',
  // Argentine
  'Mendoza',
  'San Juan',
  'Salta',
  'Patagonie',
  // Chili
  'Maipo',
  'Colchagua',
  'Casablanca',
  'Maule',
  'Aconcagua',
  // Australie
  'Barossa Valley',
  'Clare Valley',
  'Hunter Valley',
  'McLaren Vale',
  'Margaret River',
  'Yarra Valley',
  // Nouvelle-Zélande
  'Marlborough',
  'Central Otago',
  'Hawke\'s Bay',
  // Afrique du Sud
  'Stellenbosch',
  'Paarl',
  'Franschhoek',
  'Walker Bay',
  // Autriche
  'Wachau',
  'Kamptal',
  'Burgenland',
  // Autre
  'Autre',
] as const;

export const APPELLATIONS = [
  'Saint-Julien',
  'Margaux',
  'Pauillac',
  'Saint-Estèphe',
  'Saint-Emilion',
  'Pomerol',
  'Graves',
  'Châteauneuf-du-Pape',
  'Hermitage',
  'Côte-Rôtie',
  'Côtes-du-Rhône',
  'Sancerre',
  'Pouilly-Fumé',
  'Chablis',
  'Meursault',
  'Volnay',
  'Pommard',
  'Gevrey-Chambertin',
  'Chambolle-Musigny',
  'Vosne-Romanée',
  'Corton',
  'Champagne',
  'Ajaccio',
  'Aloxe-Corton',
  'Anjou',
  'Anjou-Villages',
  'Arbois',
  'Bandol',
  'Barsac',
  'Beaumes-de-Venise',
  'Beaune',
  'Bellet',
  'Bergerac',
  'Blanquette de Limoux',
  'Bordeaux',
  'Bourgogne Aligoté',
  'Bugey',
  'Cahors',
  'Canon-Fronsac',
  'Chablis Grand Cru',
  'Chablis Premier Cru',
  'Chassagne-Montrachet',
  'Chinon',
  'Clairette de Die',
  'Clos de Vougeot',
  'Collioure',
  'Condrieu',
  'Corbières',
  'Cornas',
  'Côte Chalonnaise',
  'Côte de Beaune',
  'Côtes de Blaye',
  'Côtes de Bordeaux',
  'Côtes du Jura',
  'Côtes du Ventoux',
  'Crémant d\'Alsace',
  'Crémant de Bourgogne',
  'Crémant de Loire',
  'Crozes-Hermitage',
  'Échezeaux',
  'Entre-Deux-Mers',
  'Faugères',
  'Fitou',
  'Fronton',
  'Gaillac',
  'Gigondas',
  'Graves Supérieures',
  'Haut-Médoc',
  'Irouléguy',
  'Jurançon',
  'Lalande-de-Pomerol',
  'Languedoc',
  'Lirac',
  'Listrac-Médoc',
  'Loupiac',
  'Madiran',
  'Marsannay',
  'Maury',
  'Médoc',
  'Menetou-Salon',
  'Mercurey',
  'Minervois',
  'Monbazillac',
  'Montagne-Saint-Émilion',
  'Morey-Saint-Denis',
  'Moulis-en-Médoc',
  'Muscadet',
  'Muscadet Sèvre-et-Maine',
  'Muscat de Beaumes-de-Venise',
  'Muscat de Frontignan',
  'Nuits-Saint-Georges',
  'Patrimonio',
  'Pécharmant',
  'Picpoul de Pinet',
  'Pouilly-Fuissé',
  'Pouilly-Fumé',
  'Quarts-de-Chaume',
  'Quincy',
  'Rasteau',
  'Reuilly',
  'Rivesaltes',
  'Romanée-Conti',
  'Rosé des Riceys',
  'Rully',
  'Saint-Amour',
  'Saint-Bris',
  'Saint-Chinian',
  'Saint-Émilion Grand Cru',
  'Saint-Joseph',
  'Saint-Nicolas-de-Bourgueil',
  'Saint-Péray',
  'Saint-Véran',
  'Sancerre',
  'Santenay',
  'Saumur',
  'Saumur-Champigny',
  'Savennières',
  'Sauternes',
  'Tavel',
  'Vacqueyras',
  'Vouvray',
  'Volnay',
  'Vosne-Romanée',
  'Autre',
] as const;
